line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

identifier_name:
    allowed_symbols: ["_"]
    validates_start_with_lowercase: false
    min_length:
        warning: 1
